version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    working_dir: /src
    restart: unless-stopped
    ports:
      - 127.0.0.1:${APP_PORT}:3000
    env_file: .env
    tty: true
    stdin_open: true
    depends_on:
      - db
  db:
    image: postgres:15.1-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
    ports:
      - 127.0.0.1:${DB_PORT}:5432
    volumes:
      - ../pgdata/cars_advertisements:/var/lib/postgresql/data

